//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyDescription("NCmdLiner.SolutionCreator creates a new solution by resolving a selected default " +
    "or user defined template solution.")]
[assembly: AssemblyCompany("github.com.trondr")]
[assembly: AssemblyProduct("NCmdLiner.SolutionCreator")]
[assembly: AssemblyCopyright("Copyright © <github.com.trondr> 2018")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyInformationalVersion("1.0.18150.")]
[assembly: AssemblyVersion("1.0.18150.56")]
[assembly: AssemblyFileVersion("1.0.18150.56")]


